language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t ppercca/udagram-frontend -f ./udagram-frontend/Dockerfile ./udagram-frontend
  - docker build -t ppercca/udagram-api-feed -f ./udagram-api-feed/Dockerfile ./udagram-api-feed
  - docker build -t ppercca/udagram-api-user -f ./udagram-api-user/Dockerfile ./udagram-api-user
  - docker build -t ppercca/reverse-proxy -f ./reverse-proxy/Dockerfile ./reverse-proxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ppercca/udagram-api-feed
  - docker push ppercca/udagram-api-user
  - docker push ppercca/udagram-frontend
  - docker push ppercca/simple-reverse-proxy