apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-user
  labels:
    app: app-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-user
  template:
    metadata:
      labels:
        app: app-user
    spec:
      containers:
      - name: udagram-api-user
        image: ppercca/udagram-api-user
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
